# Generated by Django 4.1.3 on 2022-11-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
